Make RTL support better.
LibChecker/LibChecker pull request #1011
Opened 2023-11-23 13:37 UTC by zhaobozhen

2023-11-29 13:49 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/features/applist/detail/ui/view/AppPropItemView.kt
> +      -1
```suggestion
      ViewGroup.LayoutParams.MATCH_PARENT
```

2023-11-29 13:54 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/features/snapshot/ui/adapter/SnapshotAdapter.kt
> +          append(LCAppUtils.getDiffString(sizeDiff, bytesDiff, isNewOrDeleted, highlightDiffColor = highlightDiffColor, diff2Suffix = " Bytes"))
why here

2023-11-29 14:00 UTC, qhy040404 requested changes

2023-11-29 14:00 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/features/snapshot/ui/adapter/SnapshotAdapter.kt
![Screenshot_2023-11-29-21-57-30-787_com absinthe libchecker debug 1](https://github.com/LibChecker/LibChecker/assets/45379733/88daa816-7b9c-44f6-8572-f944d3308654)
App name diff, API diff, `ARROW`.
Randomly versionInfo diff.

2023-11-29 15:34 UTC, zhaobozhen commented on app/src/main/kotlin/com/absinthe/libchecker/features/snapshot/ui/adapter/SnapshotAdapter.kt
> +          append(LCAppUtils.getDiffString(sizeDiff, bytesDiff, isNewOrDeleted, highlightDiffColor = highlightDiffColor, diff2Suffix = " Bytes"))
I only want to highlight diff of numbers but not the word `Bytes`

2023-11-30 01:38 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/features/snapshot/ui/adapter/SnapshotAdapter.kt
> +const val ARROW_REVERT = "←"
```kotlin
val ARROW: String get() = if (GlobalValues.locale.layoutDirection == View.LAYOUT_DIRECTION_RTL) "←" else "→"
```

2023-11-30 01:38 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/utils/IcuUtils.kt
May not be effective
![image](https://github.com/LibChecker/LibChecker/assets/45379733/e24c10c1-9b72-4bd5-9db6-632501c0acc1)

2023-11-30 02:01 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/utils/IcuUtils.kt
```kotlin
androidx.core.text.BidiFormatter.getInstance().isRtl(text)
```

2023-12-01 03:41 UTC, qhy040404 approved these changes
开摆

2023-12-01 03:55 UTC, merged