Add Signatures tab to app detail page
LibChecker/LibChecker pull request #428
Opened 2022-09-19 02:25 UTC by 4332weizi

2022-09-19 02:32 UTC, qhy040404 requested changes

2022-09-19 02:32 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/utils/ByteArray.kt
> +}
Put this file into `extensions` folder. 
Rename to 'ByteArrayExtensions.kt` is better.

2022-09-19 02:44 UTC, qhy040404 commented
#407

2022-09-19 02:49 UTC, 4332weizi commented on app/src/main/kotlin/com/absinthe/libchecker/utils/ByteArray.kt
> +}
Ok, find it! I was trying to find a package named `ktx` before :smile:

2022-09-19 15:11 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/detail/SignatureDetailBottomSheetFragment.kt
> +  private val detail by lazy { arguments?.getString(EXTRA_SIGNATURE_DETAIL).orEmpty() }
```suggestion
  private val detail by unsafeLazy { arguments?.getString(EXTRA_SIGNATURE_DETAIL).orEmpty() }
```

2022-09-19 15:11 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/detail/SignatureDetailBottomSheetFragment.kt
> +  }
```suggestion
  lifecycleScope.launch {
    val data = withContext(Dispatchers.IO) {
      detail.lines().map {
        val values = it.split(":", limit = 2)
        SignatureDetailItem(
          values.getOrNull(0).orEmpty(),
          values.getOrNull(1).orEmpty()
        )
      }.toMutableList()
    root.adapter.setNewInstance(data)
  }
```

2022-09-19 15:11 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/detail/impl/SignaturesAnalysisFragment.kt
> +    }
```suggestion
    binding.list.adapter = adapter
```

2022-09-19 15:11 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/detail/impl/SignaturesAnalysisFragment.kt
> +  }
No need to run in `scope`

2022-09-19 15:11 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/MessageDigestUtils.kt
> +  const val UTF_8 = "UTF-8"
```
Charsets.UTF_8.toString()
```

2022-09-19 15:11 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/MessageDigestUtils.kt
> +  }.getOrDefault("")
Can be implemented by okio, ref https://github.com/square/okio/blob/ce3b8b75ad5b7fc304347e3cf4f3e279a4c74695/okio/src/jvmMain/kotlin/okio/Buffer.kt

2022-09-19 15:11 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/MessageDigestUtils.kt
> +}
Like above.

2022-09-19 15:20 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/extensions/ByteArrayExtensions.kt
> +fun ByteArray.toHexString(separator: CharSequence = "") = joinToString(separator) {
```suggestion
fun ByteArray.toHexString(separator: CharSequence = ""): String = joinToString(separator) {
```

2022-09-19 15:20 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/viewmodel/DetailViewModel.kt
> +  }
Set value on main thread.

2022-09-19 15:20 UTC, Goooler commented on app/src/main/res/drawable/ic_signatures.xml
> +      android:fillColor="#D0401B"
Reformat

2022-09-20 02:08 UTC, qhy040404 requested changes

2022-09-20 02:08 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/utils/MessageDigestUtils.kt
> +  const val UTF_8 = "UTF-8"
```suggestion
  const val UTF_8 = Charsets.UTF_8.toString()
```

2022-09-20 02:08 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/viewmodel/DetailViewModel.kt
> +  }
```suggestion
  fun initSignatures() = signaturesLibItems.postValue(getSignatureChipList())
```

2022-09-20 02:19 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/utils/MessageDigestUtils.kt
> +  const val UTF_8 = "UTF-8"
> ```
> Charsets.UTF_8.toString()
> ```

If using `Charsers.UTF_8.toString()`, this value cannot be const.

2022-09-20 02:19 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/MessageDigestUtils.kt
> +  const val UTF_8 = "UTF-8"
Fine

2022-09-20 02:35 UTC, qhy040404 requested changes

2022-09-20 02:35 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/utils/MessageDigestUtils.kt
> +  const val SEPARATOR_COLON = ":"
```suggestion
  private const val UTF_8 = "UTF-8"

  private const val MD5 = "MD5"
  private const val SHA_1 = "SHA-1"
  private const val SHA_256 = "SHA-256"
  private const val SHA_512 = "SHA-512"
  private const val CRC_32 = "CRC-32"

  private const val SEPARATOR_EMPTY = ""
  private const val SEPARATOR_COLON = ":"
```

2022-09-20 02:36 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/MessageDigestUtils.kt
> +  const val SEPARATOR_COLON = ":"
https://github.com/square/okio/blob/ce3b8b75ad5b7fc304347e3cf4f3e279a4c74695/okio/src/jvmMain/kotlin/okio/Buffer.kt

2022-09-20 02:52 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/utils/MessageDigestUtils.kt
> +  const val SEPARATOR_COLON = ":"
```kotlin
// Buffer extensions defined in Buffer.kt
Buffer.md5()
Buffer.sha1()
...
```

2022-09-20 02:57 UTC, qhy040404 requested changes

2022-09-20 02:57 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/utils/MessageDigestUtils.kt
> +  const val UTF_8 = "UTF-8"
```suggestion
```

2022-09-20 02:57 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/utils/MessageDigestUtils.kt
> +  }.getOrDefault("")
```suggestion
  fun digest(
    algorithm: String,
    string: String,
    separator: CharSequence = SEPARATOR_EMPTY
  ) = runCatching {
    digest(algorithm, string.toByteArray(Charsets.UTF_8), separator)
  }.getOrDefault("")
```

2022-09-20 06:58 UTC, 4332weizi commented on app/src/main/kotlin/com/absinthe/libchecker/utils/MessageDigestUtils.kt
> +  }.getOrDefault("")
I replaced the implementation with `HashingSource` and `ByteString` of okio and moved `MessageDigestUtils` to `extensions.MessageDigestExtensions`.

2022-09-20 07:21 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/PackageUtils.kt
> +    return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
Replace `Build.VERSION_CODES.P` with 28.

2022-09-20 07:21 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/PackageUtils.kt
> +      packageInfo.signatures
```suggestion
      @Suppress("DEPRECATION")
      packageInfo.signatures
```

2022-09-20 07:21 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/PackageUtils.kt
> +  }
You can lift `.mapIndexed {}` out to be a function, and also applying to `rsaSource` & `dsaSource`

2022-09-20 07:21 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/extensions/ByteArrayExtensions.kt
> +}
Move this into `MessageDigestExtensions.kt`

2022-09-20 07:21 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/extensions/MessageDigestExtensions.kt
> +fun File.md5(separator: CharSequence = "") = HashingSource.md5(source()).hash(separator)
Declare return values on public functions.

2022-09-20 07:21 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/extensions/MessageDigestExtensions.kt
> +fun File.md5(separator: CharSequence = "") = HashingSource.md5(source()).hash(separator)
We might remove unused extensions?

2022-09-20 07:21 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/PackageUtils.kt
> +  fun getSignatures(context: Context, packageInfo: PackageInfo): List<LibStringItem> {
Maybe you can return a `Sequence` instead of `List`

2022-09-20 07:23 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/utils/PackageUtils.kt
> +    return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
```suggestion
    return if (OsUtils.atLeastP()) {
```

2022-09-20 07:38 UTC, 4332weizi commented on app/src/main/kotlin/com/absinthe/libchecker/utils/extensions/ByteArrayExtensions.kt
> +}
How about removing unused extensions in `MessageDigestExtensions.kt`, and moving all used extensions(`ByteArray.foo()`) to `ByteArrayExtensions.kt`.

2022-09-20 07:41 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/utils/extensions/ByteArrayExtensions.kt
> +}
I think we can keep using extensions only, will add them back if necessary.

2022-09-20 11:21 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/viewmodel/DetailViewModel.kt
> +  fun initSignatures() = signaturesLibItems.postValue(getSignatureChipList())
Let `getSignatureChipList()` running on IO dispatcher, `setValue` on main.

2022-09-20 11:21 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/detail/SignatureDetailBottomSheetFragment.kt
> +class SignatureDetailBottomSheetDetailFragment :
```suggestion
class SignatureDetailBSDFragment :
```

2022-09-20 11:54 UTC, Goooler commented on app/src/main/kotlin/com/absinthe/libchecker/viewmodel/DetailViewModel.kt
> +  }
Much nested, you need something like:
```kotlin
  fun initSignatures() {
    viewModelScope.launch {
      signaturesLibItems.value = getSignatureChipList()
    }
  }

  private suspend fun getSignatureChipList(): List<LibStringItemChip> = withContext(Dispatchers.IO) {
    PackageUtils.getSignatures(getApplication(), packageInfo)
      .map { LibStringItemChip(it, null) }.toList()
  }
```

2022-09-20 12:25 UTC, Goooler approved these changes
LGTM, one more thing you need to fix format, run `./gradlew formatKotlin`

2022-09-21 01:34 UTC, qhy040404 approved these changes
LGTM. However, we still need to evaluate this PR due to #407.

2022-09-22 05:36 UTC, merged