Marks the component that is not exported
LibChecker/LibChecker pull request #471
Opened 2022-10-26 01:31 UTC by qhy040404

I currently set the color of the components that are not exported to gray, but I know this is not the best display scheme.

And I don't have a harmony os device, so the test on harmony os has not be done.

2022-10-31 13:21 UTC, zhaobozhen commented
![telegram-cloud-photo-size-5-6269204212982329683-y](https://user-images.githubusercontent.com/25247117/199017055-19fef38b-c8fe-4556-8c01-cd7088ac99fd.jpg)
Yes, I think the current presentation is confusing to users and I will keep this PR until a better solution is available.

2022-10-31 14:27 UTC, qhy040404 commented
This PR will be marked as a draft until a good solution is found.

2022-12-05 14:49 UTC, Doddddd commented
只要不标注“未导出”，用什么样式用户都是猜不出来的
我觉得可以在右上角加入高级菜单，用来筛选未导出、被收录的库和排序

2022-12-06 02:06 UTC, su1216 commented
应该标注的是“已导出”而不是“未导出”。已导出可能会有安全问题，未导出是一个应用的常规设置，不应特殊标记，字体也不应使用灰色。

2022-12-06 02:34 UTC, qhy040404 commented
> 应该标注的是“已导出”而不是“未导出”。已导出可能会有安全问题，未导出是一个应用的常规设置，不应特殊标记，字体也不应使用灰色，更不能用删除线。 @Doddddd 

那可以用类似于elf的处理方式，已导出的用主题色标注。

2022-12-06 07:28 UTC, zhaobozhen commented
现在的界面设计已经不适合增加越来越多越来越复杂的功能呈现了，或许应该考虑二级页面或者更改呈现方式。

2023-01-07 07:00 UTC, zhaobozhen requested changes

2023-01-07 07:00 UTC, zhaobozhen commented on app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/main/AdvancedMenuBSDFragment.kt
> +      root.updateDemoView()
这里可以把 `updateDemoView()` 拆分一下，修改下半区域的选项可以不刷新上面的 DemoView，不然上面会闪一下。

2023-01-07 07:00 UTC, zhaobozhen commented on app/src/main/kotlin/com/absinthe/libchecker/view/applist/AdvancedMenuBSDView.kt
> +  }
这个 BottomSheet 内容过多，需要考虑做成可滚动的，不然在小屏手机上无法展示完全。

2023-01-07 07:00 UTC, zhaobozhen commented on app/src/main/kotlin/com/absinthe/libchecker/viewmodel/DetailViewModel.kt
> +              true,
HM 组件没有 exported 状态，感觉默认 false 更好一点，不然所有的组件都是染色的状态，感觉也没什么意义。

2023-01-07 11:22 UTC, zhaobozhen approved these changes

2023-01-07 11:23 UTC, merged