Fix crashes.
LibChecker/LibChecker pull request #793
Opened 2023-06-03 04:32 UTC by zhaobozhen

2023-06-03 09:39 UTC, Goooler commented
Any issuetracker?

2023-06-03 10:02 UTC, qhy040404 requested changes

2023-06-03 10:02 UTC, qhy040404 commented on app/src/main/kotlin/com/absinthe/libchecker/ui/fragment/applist/AppListFragment.kt
> +          }
And `SnapshotFragment`

2023-06-06 07:23 UTC, qhy040404 approved these changes

2023-06-06 10:06 UTC, merged